version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx4G
    steps:
      - checkout
      - run: echo "Build process is started 👯"

      - run:
          name: Create release.keystore.jks
          command: echo $RELEASE_KEYSTORE_BASE64 | base64 -d > $storeFile

      - run:
          name: Create ~/keys/keystore.properies
          command: printf 'KEYSTORE_KEY_ALIAS=%s\nKEYSTORE_KEY_PASSWORD=%s\nstoreFile=%s\nKEYSTORE_STORE_PASSWORD=%s' $KEYSTORE_KEY_ALIAS $KEYSTORE_KEY_PASSWORD $storeFile $KEYSTORE_STORE_PASSWORD > ~/keys/keystore.properties

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #- run:
          #name: Run Tests
          #command: ./gradlew lint test
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples